Pool tags support
esl/MongoosePush pull request #107
Opened 2019-10-01 11:05 UTC by kmakiela

* Added support for tags in pool configurations
* Added support for selecting pools based on tags
* Added tests for checking tags' behaviour
* Updated README
* Fixed issue with no matching pools in FCM
* Updated Sparrow ref
* Updated `FCM.Pool.Supervisor` module doc

2019-10-01 13:18 UTC, kmakiela commented
Finished work on tags and didn't want to create PR to master because of the incoming merge for `Token Auth Support` (that is included here already) - this PR is more for visibility and possible review, the option for merge will be available after merging the aforementioned PR

2019-10-10 15:45 UTC, rslota requested changes

2019-10-10 15:45 UTC, rslota commented on lib/mongoose_push/service/fcm/pool/supervisor.ex
> +    raw_tags = if is_nil(pool_config[:tags]), do: [], else: pool_config[:tags]
```suggestion
    raw_tags = pool_config[:tags] || []
```

2019-10-15 14:38 UTC, rslota approved these changes

2019-10-15 14:38 UTC, merged