Allow sending time_to_live field
esl/MongoosePush pull request #84
Opened 2019-04-05 11:21 UTC by kanes115

This PR relies on merging [this PR](todo) to Pigeon.

This PR lets mongooseim send `time_to_live` option in notifications.

2019-04-09 12:06 UTC, rslota requested changes
The code looks good in general. Tests and documentation (in `README.md`) seem to be missing though.

2019-04-09 12:06 UTC, rslota commented on test/mongoose_push_test.exs
> +          :time_to_live => time_to_live,
There is no actual check whether this is correctly set in the notification. We need that tested.

2019-04-09 12:06 UTC, rslota commented on lib/mongoose_push.ex
> +        |> Map.put(:time_to_live, request[:time_to_live])
Why do we need it here? `alert` and `data` need this to ensure those keys are in `request` map, but I don't see any logic in this PR that would require `time_to_live` to be present regardless of whether it's set or not.

2019-04-09 12:23 UTC, rslota commented on test/mongoose_push_test.exs
> +      assert notification[:time_to_live] == fcm_data["time_to_live"]
According to FCM documentation, `time_to_live` should be at the top level, among things like `priority`. This means that this check should be: 

```
assert notification[:time_to_live] == fcm_request["request_data"]["time_to_live"]
```

2019-04-11 11:30 UTC, rslota requested changes
The code looks good to me, but the documentation in `README.md` is still missing. We should add this "field" to list of supported options with a note regarding APNS incompatibility.

2019-04-11 12:49 UTC, kanes115 commented
@rslota Hope this kind of note is sufficient (the best source is the FCM documentation in this case, isn't it?)

2019-04-11 13:47 UTC, rslota approved these changes

2019-04-12 08:39 UTC, merged